    overlay_files: &TVoverlay
    - file: gradient.yml
    - pmm: resolution
      template_variables:
        horizontal_align: left
        vertical_align: top
        font_color: '#ffffffff'
        back_color: '#00000000'
        back_radius: 8
        use_edition: false
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
        use_dvhdr: false
        use_plus: false
        use_dv: false
        use_hdr: true
    #- default: streaming
    - default: network
    #- default: studio
      template_variables:
        horizontal_align: center
        vertical_align: top
        back_color: '#00000000' #'#00000066'
        back_radius: 8
        #region: AT
    - pmm: languages
      template_variables:
        horizontal_position: right
        vertical_position: bottom
        flag_alignment: right
        style: half
        font_color: '#ffffff88'
        back_color: '#00000000'
        back_radius: 8
        overlay_limit: 10
        languages: [en, de, fr, es, pt, ja, ko, zh, da, ru, it, hi, te, fa, th, nl, no, is, sv, tr, pl, cs, uk, hu, ar, bg, bn, bs, ca, cy, el, et, eu, fi, tl, fil, gl, he, hr, id, ka, kk, kn, la, lt, lv, mk, ml, mr, ms, nb, nn, pa, ro, sk, sl, sq, sr, so, sw, ta, ur, vi, ln, wo, myn, iu, rom, am, su, zu, lb, mos]
    - pmm: status
      template_variables:
        horizontal_align: left   # center
        horizontal_offset: 20   # = audience
        vertical_align: bottom
        vertical_offset: 124   # TOP = audience + 107 OR BOTTOM = audience - 59
        back_height: 66
        back_radius: 8
        back_width: 374 # 382   # 376
        font: config/fonts/Poppins-Bold.ttf
        font_size: 60
        use_airing: true
        use_returning: true
        use_canceled: true
        use_ended: true
        font_color_airing: '#4b6a8888' #'#00000088'
        font_color_returning: '#4b6a8888'
        font_color_canceled: '#ffffff88'
        font_color_ended: '#ffffff88'
        back_color_airing: '#44D90A88'
        back_color_returning: '#F5C70088'
        back_color_canceled: '#E9060688'
        back_color_ended: '#00000066'
    - file: rating_imdb_parental.yml
      template_variables:
        horizontal_align: left
        horizontal_offset: 73   # = audience
        vertical_align: bottom
        vertical_offset: 32   # = audience
    - pmm: commonsense
      template_variables:
        horizontal_align: left
        vertical_align: bottom
        horizontal_offset: 12   # audience - 9
        vertical_offset: 12   # audience - 8
        font_color: '#ffffffff'
        font_color_18: '#ff0808ff'
        font_color_nr: '#696969ff'
        back_color: '#000000'
        font: config/fonts/Poppins-Bold.ttf
        font_size: 58
        font_size_nr: 48
        back_radius: 61
        back_width: 123
        back_height: 123
        post_text: ''
        addon_position: bottom
        file: ''
    - file: rating_audience.yml
      template_variables:
        horizontal_align: left
        horizontal_offset: 20
        vertical_align: bottom
        vertical_offset: 20
