blank_issues_enabled: false
contact_links:
  - name: Plex Meta Manager Issue
    url: https://github.com/meisnate12/Plex-Meta-Manager/issues/new/choose
    about: Please post issues for Plex Meta Manager on this repository.
  - name: Plex Meta Manager Wiki
    url: https://metamanager.wiki
    about: Check the wiki for information.
  - name: Discord
    url: https://discord.gg/NfH6mGFuAB
    about: Use the Plex Meta Manager Discord to ask for support.
