######################################################
#         Smart Charts & Releases Collections        #
#      Created by Yozora, Bullmoose20, & Sohjiro     #
#                                                    #
#  Call this from your config.yml (Movie only):      #
#     metadata_path:                                 #
#       - git: PMM/movie/chart                       #
#         template_variables:                        #
#           schedule_separator: never                #
#           collection_mode: hide                    #
#           collection_section: "02"                 #
######################################################

external_templates:
  git: PMM/templates
  template_variables:
    collection_section: "02"

collections:
  Movie Chart Collections:
    template:
      - name: separator
        separator: movie_chart

  Newly Released Movies:
    template:
      - name: Newly_Released_Movies
      - name: chart
        image: Newly Released Movies
      - name: shared
    summary: A collection of newly-released movies in cinema and on streaming services
    smart_filter:
      all:
        release.after: 01/01/2022
      sort_by: release.desc

  TMDb Trending Movies:
    template:
      - name: TMDb_Trending_Movies
      - name: chart
        image: TMDb Trending Movies
      - name: shared
    tmdb_trending_weekly: 250
    summary: A collection of movies trending on TMDb
    collection_order: custom

  TMDb Popular Movies:
    template:
      - name: TMDb_Popular_Movies
      - name: chart
        image: TMDb Popular Movies
      - name: shared
    tmdb_popular: 250
    summary: A collection of the most watched movies according to TMDb.
    collection_order: custom

  TMDb Now Playing Movies:
    template:
      - name: TMDb_Now_Playing_Movies
      - name: chart
        image: TMDb Now Playing Movies
      - name: shared
    tmdb_now_playing: 250
    summary: A collection of movies that people are currently watching.
    collection_order: custom

  IMDb Top 250 Movies:
    # sort_title: !01_~<<collection_name>>
    template:
      - name: IMDb_Top_250_Movies
      - name: chart
        image: IMDb Top 250 Movies
      - name: shared
    imdb_chart: top_movies
    collection_order: custom
