######################################################
#                Producer Collections                #
#      Created by Yozora, Bullmoose20, & Sohjiro     #
#                                                    #
#  Call this from your config.yml (Movie only):      #
#     metadata_path:                                 #
#       - git: PMM/movie/producer                    #
######################################################

templates:
  producer_dynamic:
    collection_mode: hide
    sort_title: +19_<<collection_name>>
    tmdb_person: <<value>>
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/people/<<key_encoded>>.jpg
    smart_filter:
      all:
        producer: tmdb

collections:
  Producers Collections:
    blank_collection: true
    collection_mode: hide
    sort_title: +19_+Producer Collections
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/separators/producer.jpg

dynamic_collections:
  Top Producers:
    type: producer
    template: producer_dynamic
    title_format: <<title>> (Producer)
    data:
      depth: 5
      limit: 25
      