metadata:               #Posters found here: https://theposterdb.com/poster/201516

  "Trainspotting (1996)":
    title: "Trainspotting"
    year: 1996
    url_poster: https://theposterdb.com/api/assets/201515

  "T2 Trainspotting (2017)":
    title: "T2 Trainspotting"
    year: 2017
    url_poster: https://theposterdb.com/api/assets/201516
