#####################################################
#              Network Collections                   #
######################################################

templates:
  network:
    smart_filter:
      sort_by: release.desc
      validate: false
      any:
        network: <<network>>
    sort_title: +03_<<collection_name>>
    url_background: https://wallpaper.dog/large/20509069.jpg
#    schedule: weekly (sunday)

collections:
  ABC Shows:
    template: { name: network, network: "ABC, ABC (AU), ABS (US), ABC Comedy, ABC Family, ABC Me, ABC Spark, ABC.com, ABC1, ABC3" }
    url_poster: https://i.imgur.com/mlpeRrY.jpg

  Adult Swim Shows:
    template: { name: network, network: "Adult Swim" }
    url_poster: https://i.imgur.com/0UV96ev.jpg

  AMC Shows:
    template: { name: network, network: "AMC, AMC+" }
    url_poster: https://i.imgur.com/CaALafB.jpeg

  A&E Shows:
    template: { name: network, network: "A&E" }
    url_poster: https://i.imgur.com/LxSlmgQ.jpg

  AppleTV+ Shows:
    template: { name: network, network: "Apple Music, Apple TV+" }
    url_poster: https://i.imgur.com/0c9c9lp.jpg

  BBC Shows:
    template: { name: network, network: "BBC, BBC America, BBC Choice, BBC First, BBC Four, BBC HD, BBC iPlayer, BBC One, BBC Two, BBC Three, BBC UKTV, CBBC, Cbeebies" }
    url_poster: https://i.imgur.com/6eaLmTK.jpg

  Cartoon Network Shows:
    template: { name: network, network: "Cartoon Network" }
    url_poster: https://i.imgur.com/LmTQF62.jpeg

  CBS Shows:
    template: { name: network, network: "CBS, CBS All Access, CBS Reality, CBS Reality (UK), CBS.com" }
    url_poster: https://i.imgur.com/jLkXT2o.jpeg

  Channel 4 Shows:
    template: { name: network, network: "Channel 4, E4, More4, 4Seven, Film4" }
    url_poster: https://i.imgur.com/0d49D8z.jpeg
    #visible_library: true
    #visible_home: false
    #visible_shared: true

  Cinemax Shows:
    template: { name: network, network: "Cinemax" }
    url_poster: https://i.imgur.com/VD7OWQn.jpg

  Comedy Central Shows:
    template: { name: network, network: "Comedy Central, Comedy Central (UK)" }
    url_poster: https://i.imgur.com/U6YRJ1k.jpg

  Cooking Channel:
    template: { name: network, network: "Cooking Channel" }
    url_poster: https://i.imgur.com/4Ft7kFB.jpeg

  Discovery Shows:
    template: { name: network, network: "Discovery, Discovery Channel, Discovery Channel (AU), Discovery Channel (CA), Discovery Channel (UK), Discovery Health Channel, Discovery Kids, Discovery Life, Discovery Real Time, Discovery Turbo, Discovery Turbo UK, Discovery+" }
    url_poster: https://i.imgur.com/07aDOXW.jpg

  Disney+ Shows:
    template: { name: network, network: "Disney Channel, Disney Channel (UK), Disney Junior, Disney XD, Disney+, Disney+ Hostar" }
    url_poster: https://i.imgur.com/j55whvT.jpg
    #visible_library: true
    #visible_home: false
    #visible_shared: true

  ESPN Shows:
    template: { name: network, network: "ESPN, ESPN+" }
    url_poster: https://i.imgur.com/EIBGK8V.jpeg

  FOX Shows:
    template: { name: network, network: "FX, FOX, Fox Action Movies, Fox Business Network, Fox Kids, Fox Premium Series, FOX Sports 1, Fox Sports Networks" }
    url_poster: https://i.imgur.com/GCYzw3R.jpg

  HBO Shows:
    template: { name: network, network: "HBO, HBO Canada, HBO Europe, HBO Max" }
    url_poster: https://i.imgur.com/u4UPWsG.jpg

  HGTV Shows:
    template: { name: network, network: "HGTV, HGTV Canada" }
    url_poster: https://i.imgur.com/m8aW7PF.jpg

  History Shows:
    template: { name: network, network: "History, History (CA), History (UK)" }
    url_poster: https://i.imgur.com/ONFZrZ8.jpeg

  Hulu Shows:
    template: { name: network, network: "Hulu" }
    url_poster: https://i.imgur.com/0BLtVsI.jpg

  Investigation Discovery Shows:
    template: { name: network, network: "Investigation Discovery" }
    url_poster: https://i.imgur.com/Oridpmb.jpeg

  ITV Shows:
    template: { name: network, network: "ITV, ITV2, ITV3, ITV4, ITVBe, CITV" }
    url_poster: https://i.imgur.com/JOgpjDq.jpg
    #visible_library: true
    #visible_home: false
    #visible_shared: true

  MTV Shows:
    template: { name: network, network: "MTV, MTV (AU/NZ), MTV (UK), MTV2, MTV3" }
    url_poster: https://i.imgur.com/wLJpxbQ.jpg

  National Geographic Shows:
    template: { name: network, network: "National Geographic, National Geographic (UK), National Geographic Brasil, National Geographic Channel, National Geographic Wild" }
    url_poster: https://i.imgur.com/dwxYxwK.jpg

  Nickelodeon Shows:
    template: { name: network, network: "Nick Jr., Nickelodeon, Nicktoons, TeenNick" }
    url_poster: https://i.imgur.com/DPcPQbU.jpeg

  NBCUniversal Shows:
    template: { name: network, network: "Bravo, CNBC, E!, MSNBC, NBC, Oxygen, Peacock, SyFy" }
    url_poster: https://i.imgur.com/s3MFG59.jpg

  Netflix Shows:
    template: { name: network, network: "Netflix" }
    url_poster: https://i.imgur.com/T0etwew.jpg
    #visible_library: true
    #visible_home: false
    #visible_shared: true

  PBS Shows:
    template: { name: network, network: "PBS, PBS Kids" }
    url_poster: https://i.imgur.com/rez9Jeq.jpeg

  Prime Video Shows:
    template: { name: network, network: "Amazon, Amazon Prime Video, Prime Video" }
    url_poster: https://i.imgur.com/5gd7Lyw.jpg

  Showtime Shows:
    template: { name: network, network: "Showtime" }
    url_poster: https://i.imgur.com/ZhsLqS9.jpg

  Sky Shows:
    template: { name: network, network: "Sky 1, Sky Arts, Sky Atlantic, Sky Atlantic (UK), Sky Cinema, Sky Crime, Sky Documentaries, Sky Living, Sky Max, Sky Nature, Sky One, Sky Sports, Sky Two, Sky Witness, Sky1" }
    url_poster: https://i.imgur.com/qBS4e5P.jpg

  Stan Shows:
    template: { name: network, network: "Starz" }
    url_poster: https://i.imgur.com/HHaGyJt.jpeg

  Starz Shows:
    template: { name: network, network: "Starz" }
    url_poster: https://i.imgur.com/r8bnIEy.jpg

  TBS Shows:
    template: { name: network, network: "TBS" }
    url_poster: https://i.imgur.com/eVGITgO.jpg

  YouTube Shows:
    template: { name: network, network: "YouTube, YouTube Premium" }
    url_poster: https://i.imgur.com/xoWEueb.jpg
