#############################################################
#                  IMDb Chart Collections                   #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/imdb                                #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#          # For each collection use the "key" to set       #
#          # the options.                                   #
#          # Available collections                          #
#          #   KEY              COLLECTION                  #
#          #   popular          IMDb Popular                #
#          #   top              IMDb Top 250                #
#          #   lowest           IMDb Lowest                 #
#                                                           #
#          # Available options. Replace "key"               #
#          # with desired collection.                       #
#                                                           #
#          # Turn the collection on/off                     #
#          use_key: true                                    #
#          # Set visible_library for collection             #
#          visible_library_key                              #
#          # Set visible_home for collection                #
#          visible_home_key:                                #
#          # Set visible_shared for collection              #
#          visible_shared_key:                              #
#          # Add missing to rdarr                           #
#          radarr_add_missing_key:                          #
#          # Set tag for radarr                             #
#          radarr_tag_key:                                  #
#############################################################

external_templates:
  git: PMM/templates
  template_variables:
    collection_section: "01"

templates:

  imdb:
    imdb_chart: <<chart>>_<<library_type>>s
    collection_order: custom
    sync_mode: sync

collections:

  IMDb Popular:
    template:
      - name: imdb
        chart: popular
      - name: chart_shared
        key: popular

  IMDb Top 250:
    template:
      - name: imdb
        chart: top
      - name: chart_shared
        key: top

  IMDb Lowest Rated:
    imdb_chart: lowest_rated
    collection_order: custom
    sync_mode: sync
    template:
      - name: chart_shared
        key: lowest
        check_library: movie
