#############################################################
#                Charts Separator Collection                #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#    metadata_path:                                         #
#      - git: PMM/chart/separator                           #
#        template_variables:                                #
#          # Turn the separator collection on/off           #
#          use_separator: true                              #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#############################################################

external_templates:
  git: PMM/templates
  template_variables:
    collection_section: "01"

collections:
  Chart Collections:
    template:
      - name: separator
        separator: chart
