#############################################################
#             Basic Tautulli Chart Collections              #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  REQUIRES TAUTULLI AUTHENTICATION                         #
#  https://metamanager.wiki/en/latest/config/tautulli.html  #
#                                                           #
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/tautulli                            #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#          # Turn the Plex Popular collection on/off        #
#          use_popular: true                                #
#          # Determines collection order in it's section    #
#          order_popular:                                   #
#          # Set visible_library for Plex Popular           #
#          visible_library_popular:                         #
#          # Set visible_home for Plex Popular              #
#          visible_home_popular:                            #
#          # Set visible_shared for Plex Popular            #
#          visible_shared_popular:                          #
#          # Set list_size for Plex Popular                 #
#          list_size_popular:                               #
#          # Set list_days for Plex Popular                 #
#          list_days_popular:                               #
#############################################################

external_templates:
  git: PMM/templates
  template_variables:
    collection_section: "01"

templates:
  tautulli:
    default:
      list_days_popular: 30
      list_size_popular: 20
    summary: A collection of <<library_type>>s Popular on Plex
    tautulli_popular:
      list_days: <<list_days_popular>>
      list_size: <<list_size_popular>>
      list_buffer: 20

collections:
  Plex Popular:
    template:
      - name: tautulli
      - name: customsync
      - name: chart_shared
        key: popular
