#############################################################
#                  Trakt Chart Collections                  #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  REQUIRES TRAKT AUTHENTICATION                            #
#  https://metamanager.wiki/en/latest/config/trakt.html     #
#                                                           #
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/trakt                               #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#          # For each collection use the "key" to set       #
#          # the options.                                   #
#          # Available collections                          #
#          #   KEY              COLLECTION                  #
#          #   collected        Trakt Collected             #
#          #   popular          Trakt Popular               #
#          #   recommended      Trakt Recommended           #
#          #   trending         Trakt Trending              #
#          #   watched          Trakt Watched               #
#                                                           #
#          # Available options. Replace "key" with the      #
#          # desired collection's key from the chart above. #
#                                                           #
#          # Customize summary of collection                #
#          summary_key: A collection of ...                 #
#          # Turn the collection on/off                     #
#          use_key: true                                    #
#          # Determines collection order in its section     #
#          order_key:                                       #
#          # Determines collection order of the collection  #
#          collection_order_key: custom                     #
#          # Set visible_library for the collection         #
#          visible_library_key:                             #
#          # Set visible_home for the collection            #
#          visible_home_key:                                #
#          # Set visible_shared for the collection          #
#          visible_shared_key:                              #
#          # Set limit for the collection                   #
#          limit_key: 100                                   #
#          # Adds missing from the collection to radarr     #
#          radarr_add_missing_key:                          #
#          # Adds missing from the collection to sonarr     #
#          sonarr_add_missing_key:                          #
#          # Radarr Folder to add to                        #
#          radarr_folder_key:                               #
#          # Sonarr Folder to add to                        #
#          sonarr_folder_key:                               #
#          # Radarr Tag for added missing                   #
#          radarr_tag_key:                                  #
#          # Sonarr Tag for added missing                   #
#          sonarr_tag_key:                                  #
#          # Radarr Tag for existing items                  #
#          item_radarr_tag_key:                             #
#          # Sonarr Tag for existing items                  #
#          item_sonarr_tag_key:                             #
#############################################################

external_templates:
  git: PMM/templates
  template_variables:
    collection_section: "01"

templates:
  trakt:
    default:
      limit_<<key>>: 100
      summary_<<key>>: A collection of Trakt's Weekly <<collection_name>> List
    trakt_chart:
      chart: <<key>>
      limit: <<limit_<<key>>>>
    summary: <<summary_<<key>>>>

dynamic_collections:
  Trakt:
    type: custom
    data:
      collected: Collected
      popular: Popular
      recommended: Recommended
      trending: Trending
      watched: Watched
    title_format: Trakt <<key_name>>
    template:
      - trakt
      - shared
      - arr
      - custom
