########################################################################
##                   Plex-Meta-Manager by JJJonesJr33                 ##
########################################################################

## This file is a template remove the .template to use the file

libraries: # Library mappings must have a colon (:) placed after them
  Movies: # Must match you library that is shown within plex
    metadata_path:
      - file: config/Movies.yml
  Movies 4K: # Must match you library that is shown within plex
    metadata_path:
      - file: config/Movies 4K.yml
  TV Shows: # Must match you library that is shown within plex
    metadata_path:
      - file: config/TV Shows.yml
  TV Shows 4K: # Must match you library that is shown within plex
    metadata_path:
      - file: config/TV Shows 4K.yml
  Anime: # Must match you library that is shown within plex
    metadata_path:
      - file: config/Anime.yml
settings: # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_missing: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_user: all
  verify_ssl: true
webhooks: # If you do not use webhooks remove this from the config
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  changes: notifiarr
plex: # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.1.2:32400/
  token: #####################
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb: # REQUIRED for the script to run - to get a key you must follow https://developers.themoviedb.org/3/getting-started/introduction
  apikey: #####################
  language: en
tautulli: # Can be individually specified per library as well
  url: http://192.168.1.2:8181/
  apikey: #####################
omdb:
  apikey: #####################
notifiarr: # If you do not use webhooks remove this from the config
  apikey: #####################
anidb: # Not required for AniDB builders unless you want mature content
  username: 
  password: ########
radarr: # Can be individually specified per library as well - set up by following https://github.com/meisnate12/Plex-Meta-Manager/wiki/Radarr-Attributes
  url: http://192.168.1.2:7878/
  token: #####################
  add_missing: ture
  add_existing: false
  root_folder_path: /media/movies
  monitor: true
  availability: released
  quality_profile: 1080p
  tag:
  search: true
  radarr_path:
  plex_path:
sonarr: # Can be individually specified per library as well - set up by following https://github.com/meisnate12/Plex-Meta-Manager/wiki/Sonarr-Attributes
  url: http://192.168.1.2:8989
  token: #####################
  version: v3
  add: false
  add_existing: false
  root_folder_path: /media/tv
  monitor: all
  quality_profile: 1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
trakt: # needed for both the movies and tv shows yml configs - set up by following https://github.com/meisnate12/Plex-Meta-Manager/wiki/Trakt-Attributes
  client_id: #####################
  client_secret: #####################
  authorization:
    access_token: 
    token_type: 
    expires_in: 
    refresh_token: 
    scope: public
    created_at: 
mal: # Only needed if you have a anime library - set up by following https://github.com/meisnate12/Plex-Meta-Manager/wiki/MyAnimeList-Attributes
  client_id: 
  client_secret: 
  authorization:
    access_token: 
    token_type: 
    expires_in: 
    refresh_token: 
