######################################################
#                Producer Collections                #
#          Created by Yozora and Bullmoose20         #
#                                                    #
######################################################

templates:
  producer_dynamic:
    collection_mode: hide
    sort_title: +19_<<collection_name>>
    tmdb_person: <<producer>>
    plex_search:
      all:
        producer: tmdb

collections:
  Producers Collections:
    blank_collection: true
    collection_mode: hide
    sort_title: +19_+Producer Collections
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/common/people/producer/Producer%20Collections.jpg

dynamic_collections:
  Top Producers:         # mapping name does not matter just needs to be unique
    type: producer
    template: producer_dynamic
    title_format: <<title>> (Producer)
    data:
      depth: 5
      limit: 25
      