## config.yml

libraries:
  Movies:
    library_type: movie
    operations:
      - schedule: daily
        delete_unmanaged_collections: false
#      - schedule: weekly(thursday)
#        mass_audience_rating_update: mdb_average
#        mass_critic_rating_update: mdb_metacritic
#        mass_user_rating_update: imdb
#        mass_content_rating_update: mdb
#        mass_genre_update: imdb
#      - schedule: weekly(thursday)
#        mass_poster_update:
#          source: tmdb
#          seasons: false
#          episodes: false
    collection_files:
#    - file: config/collections/movie/_maintenance.yml
#    - file: config/collections/movie/_radarr.yml
    - file: config/collections/movie/010_suggested.yml
#    - file: config/collections/movie/020_unwatched.yml
    - file: config/collections/movie/030_watched.yml
    - file: config/collections/movie/040_seasonal.yml
    - file: config/collections/movie/080_year_top.yml
      schedule: weekly(monday)
    - file: config/collections/movie/090_decades_top.yml
      schedule: weekly(tuesday)
#    - file: config/collections/movie/100_awards.yml
#      schedule: weekly(wednesday)
    - file: config/collections/movie/110_genre_popular.yml
    - file: config/collections/movie/120_genre_top.yml
      schedule: weekly(thursday)
#    - file: config/collections/movie/130_subgenre_top.yml
#    - file: config/collections/movie/140_studio.yml
#      schedule: weekly(wednesday)
#    - file: config/collections/movie/200_collections.yml
#      schedule: weekly(sunday)
#    - file: config/collections/movie/050_parental_sync.yml
#    - file: config/collections/movie/050_parental.yml
#    - file: config/collections/movie/060_documentary.yml
#    - file: config/collections/movie/070_standup.yml
  TV:
    library_type: show
    operations:
      - schedule: daily
        delete_unmanaged_collections: false
#      - schedule: weekly(friday)
#        mass_audience_rating_update: mdb_average
#        mass_critic_rating_update: mdb_metacritic
#        mass_user_rating_update: imdb
#        mass_content_rating_update: mdb
#        mass_genre_update: imdb
#      - schedule: weekly(sunday)
#        mass_poster_update:
#          source: tmdb
#          seasons: true
#          episodes: false
    collection_files:
#    - file: config/collections/show/_maintenance.yml
#    - file: config/collections/show/_sonarr.yml
    - file: config/collections/show/010_suggested.yml
#    - file: config/collections/show/020_unwatched.yml
    - file: config/collections/show/030_watched.yml
    - file: config/collections/show/060_year_top.yml
      schedule: weekly(monday)
    - file: config/collections/show/070_decades_top.yml
      schedule: weekly(wednesday)
#    - file: config/collections/show/080_awards.yml
#      schedule: weekly(thursday)
    - file: config/collections/show/090_genre_popular.yml
    - file: config/collections/show/100_genre_top.yml
      schedule: weekly(saturday)
#    - file: config/collections/show/110_network.yml
#    - file: config/collections/show/040_parental_sync.yml
#    - file: config/collections/show/040_parental.yml
#    - file: config/collections/show/050_documentary.yml
#  KIDS:
#    library_type: show
#    operations:
#      - schedule: daily
#        delete_unmanaged_collections: false
#      - schedule: weekly(friday)
#        mass_audience_rating_update: mdb_average
#        mass_critic_rating_update: mdb_metacritic
#        mass_user_rating_update: imdb
#        mass_content_rating_update: mdb
#        mass_genre_update: imdb
#      - schedule: weekly(saturday)
#        mass_poster_update:
#          source: tmdb
#          seasons: true
#          episodes: false
#    collection_files:
#    - file: config/collections/show/_maintenance.yml
#    - file: config/collections/show/_sonarr.yml
#    - file: config/collections/show/040_parental_sync.yml
#    - file: config/collections/show/040_parental.yml
settings:
  assets_for_all: false
  asset_depth: 0
  asset_directory:
  asset_folders: false
  cache: true
  cache_expiration: 60
  check_nightly: false
  create_asset_folders: false
  custom_repo:
  default_collection_order:
  delete_below_minimum: false
  delete_not_scheduled: false
  dimensional_asset_rename: false
  download_url_assets: true
  ignore_ids:
  ignore_imdb_ids:
  item_refresh: false
  item_refresh_delay: 0
  minimum_items: 1
  missing_only_released: false
  only_filter_missing: false
  playlist_exclude_users:
  playlist_report: true
  playlist_sync_to_users: all
  prioritize_assets: false
  released_missing_only: false
  run_again_delay: 5
  run_order:
  - collections
  - metadata
  - operations
  - overlays
  save_missing: false
  show_asset_not_needed: true
  show_filtered: false
  show_missing: false
  show_missing_assets: true
  show_missing_episode_assets: false
  show_missing_season_assets: false
  show_options: false
  show_unconfigured: true
  show_unmanaged: false
  sync_mode: sync
  tvdb_language: default
  verify_ssl: false
plex:
  url:
  token:
  timeout: 180
  clean_bundles: false
  empty_trash: false
  optimize: false
radarr:
  url:
  token:
  add_missing: false
  add_existing: false
  root_folder_path:
  monitor: true
  availability: announced
  quality_profile:
  tag:
  search: false
  radarr_path:
  plex_path:
  upgrade_existing: false
sonarr:
  url:
  token:
  add_missing: false
  add_existing: false
  root_folder_path:
  monitor: all
  quality_profile:
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
tmdb:
  apikey:
  language: en
  cache_expiration: 60
  region:
mdblist:
  apikey:
  cache_expiration: 60
trakt:
  client_id:
  client_secret:
  pin:
