######################################################
#                Studio Collections                  #
######################################################
templates:
  Studio:
    optional:
      - company
    tmdb_company: <<company>>
    sort_title: +2_<<collection_name>>
    sync_mode: sync
    smart_label: release.desc
collections:
  Aardman:
    template: { name: Studio, company: 297 }
    summary: Aardman Animations, Ltd. is a British animation studio based in Bristol, England. Aardman is known for films made using stop-motion clay animation techniques, particularly those featuring Plasticine characters Wallace and Gromit.
    url_poster: https://theposterdb.com/api/assets/137887
  Blue Sky:
    template: { name: Studio, company: 9383 }
    summary: Blue Sky Studios, Inc. is an American computer animation film studio based in Greenwich, Connecticut. It is a subsidiary of 20th Century Animation, a division of Disney Studios Content.
    url_poster: https://theposterdb.com/api/assets/103278
  DreamWorks:
    template: { name: Studio, company: 521 }
    filters:
      collection.not: Aardman
    summary: DreamWorks Animation LLC (also simply known as DreamWorks) is an American animation studio and a subsidiary of Universal Pictures, itself a subsidiary of Comcast's NBCUniversal. It is based in Glendale, California, and produces animated feature films, television programs, and online virtual games.
    url_poster: https://theposterdb.com/api/assets/159964
  Illumination Entertainment:
    template: { name: Studio, company: 6704 }
    summary: Illumination is an American film and animation studio founded by Chris Meledandri in 2007 and owned by Universal Pictures, a division of NBCUniversal, which is itself a division of Comcast. Meledandri produces the films, while Universal finances and distributes all the films. The studio is responsible for the Despicable Me and The Secret Life of Pets franchises and the film adaptations of Dr. Seuss’ books The Lorax and How the Grinch Stole Christmas. The Minions, characters from the Despicable Me series, are the studio's mascots.
    url_poster: https://theposterdb.com/api/assets/202590
  Laika Entertainment:
    template: { name: Studio, company: 11537 }
    summary: Laika is an American stop-motion animation studio. It is best known for it's stop-motion films Coraline, ParaNorman, The Boxtrolls, Kubo and the Two Strings, and Missing Link.
    url_poster: https://theposterdb.com/api/assets/103277
  Pixar:
    template: { name: Studio, company: 3 }
    summary: Pixar Animation Studios, commonly known as Pixar, is an American computer animation studio based in Emeryville, California, a subsidiary of Disney Studios Content owned by The Walt Disney Company. Pixar began in 1979 as part of the Lucasfilm computer division, known as the Graphics Group, before its spin-off as a corporation on February 3, 1986, with funding from Apple co-founder Steve Jobs, who became its majority shareholder. Disney purchased Pixar in 2006 at a valuation of $7.4 billion by converting each share of Pixar stock to 2.3 shares of Disney stock, a transaction that resulted in Jobs becoming Disney's largest single shareholder at the time. Pixar is best known for its feature films technologically powered by RenderMan, the company's own implementation of the industry-standard RenderMan Interface Specification image-rendering application programming interface. Luxo Jr., a desk lamp from the studio's 1986 short film of the same name, is the studio's mascot.
    url_poster: https://theposterdb.com/api/assets/148076
  Studio Ghibli:
    template: { name: Studio, company: 10342 }
    summary: Studio Ghibli Inc. is a Japanese animation film studio headquartered in Koganei, Tokyo. The studio is best known for its animated feature films, and has also produced several short films, television commercials, and one television film. The studio’s mascot and most recognizable symbol is the character, Totoro, a giant cat-like spirit from the 1988 classic, My Neighbor Totoro.
    url_poster: https://theposterdb.com/api/assets/103281
    url_background: https://wallpapercave.com/wp/aWaXW72.jpg
  Sony Pictures Animation:
    template: { name: Studio, company: 2251 }
    summary: Sony Pictures Animation Inc. is an American animation studio owned by Sony Entertainment's Sony Pictures Entertainment through their Motion Picture Group division and founded on May 9, 2002. The studio's films are distributed worldwide by Sony Pictures Releasing under their Columbia Pictures label, while all direct-to-video releases are released by Sony Pictures Home Entertainment.
    url_poster: https://theposterdb.com/api/assets/174163
  Warner Animation Group:
    template: { name: Studio, company: 25120 }
    summary: The Warner Animation Group (WAG) is an American animation studio that is the feature animation division of Warner Bros. Entertainment. Established on January 7, 2013, the studio is the successor to the dissolved 2D traditional hand-drawn animation studio Warner Bros. Feature Animation, which shut down in 2003 and the dissolved family film division Warner Bros. Family Entertainment, which shut down in 2009. The entity is also a sister animation studio of the regular animation studio Warner Bros. Animation
    url_poster: https://theposterdb.com/api/assets/103280
  Walt Disney Animation Studios:
    template: { name: Studio }
    imdb_list: https://www.imdb.com/list/ls059383351/
    summary: Walt Disney Animation Studios (WDAS), sometimes shortened to Disney Animation, is an American animation studio that creates animated features and short films for The Walt Disney Company. Founded on October 16, 1923 by brothers Walt Disney and Roy O. Disney, it is one of the oldest-running animation studios in the world. It is currently organized as a division of Walt Disney Studios and is headquartered at the Roy E. Disney Animation Building at the Walt Disney Studios lot in Burbank, California.
    url_poster: https://theposterdb.com/api/assets/152809
  Walt Disney Pictures:
    template: { name: Studio }
    imdb_list: https://www.imdb.com/list/ls077114097/
    summary: Walt Disney Pictures is an American film production studio of The Walt Disney Studios, which is owned by The Walt Disney Company. The studio is the flagship producer of live-action feature films within the Walt Disney Studios unit, and is based at the Walt Disney Studios in Burbank, California. Animated films produced by Walt Disney Animation Studios and Pixar Animation Studios are also released under this brand. Walt Disney Studios Motion Pictures distributes and markets the films produced by Walt Disney Pictures.
    url_poster: https://theposterdb.com/api/assets/167260