## This file is a template remove the .template to use the file

libraries: # Library mappings must have a colon (:) placed after them
  Movies:
    library_name: Movies
    metadata_path:
      - /config/metadata/Awards.yml
      - /config/metadata/Decades.yml
      - /config/metadata/Genres.yml
      - /config/metadata/Holiday.yml
    # - /config/metadata/Studios.yml
      - /config/metadata/Suggestions.yml
    operations:
      assets_for_all: false
      split_duplicates: true
      delete_unmanaged_collections: true
  Movies 4K:
    library_name: Movies 4K
    metadata_path:
      file: /config/metadata/Overlay.yml
    operations:
      assets_for_all: false
      split_duplicates: true
      delete_unmanaged_collections: true
settings: # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory:
    - config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: false
  save_missing: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_user:
  verify_ssl: true
webhooks:
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  changes: notifiarr
plex: # REQUIRED - see https://github.com/meisnate12/Plex-Meta-Manager/wiki/Plex-Attributes
  url: http://192.168.1.2:32400/
  token: 
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:  # REQUIRED for the script to run - to get a key you must follow https://developers.themoviedb.org/3/getting-started/introduction
  apikey: 6bc39032851ad6285e3a2bfeaf19b5d5
  language: en
tautulli: # Can be individually specified per library as well
  url: http://192.168.1.2:8181/
  apikey: 
omdb:
  apikey: 
notifiarr:
  apikey: 
anidb: # Not required for AniDB builders unless you want mature content
  username: 
  password: 
trakt:
  client_id: 
  client_secret: 
  authorization:
    access_token: 
    token_type: 
    expires_in: 
    refresh_token: 
    scope: public
    created_at: 
