name: Release

on:
  release:
    types: [ published ]

jobs:

  release-notification:

    runs-on: ubuntu-latest
    steps:

      - name: Send Discord Release Notification
        uses: meisnate12/discord-notifications@master
        with:
          webhook_id: ${{ secrets.RELEASE_WEBHOOK_ID }}
          webhook_token: ${{ secrets.RELEASE_WEBHOOK_TOKEN }}
          release: true
          title: Plex Meta Manager Defaults VERSION
          message: "<@&1021857386132144202> - The PMM Default Metadata & Overlays (use `!defaults` to learn more) have been updated as follows"
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/.github/pmm.png